title: René Cano
description: ITC Student | Software & Data Projects
theme: minima
author: René Cano
url: https://renecano.github.io

header_pages:
  - home.md
  - projects.md
  - blog.md
  - about.md
